apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  labels:
    toll: Helm
  namespace: argocd
spec:
  destination:
    namespace: prometheus
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    automated: 
      prune: true 
      selfHeal: true 
    syncOptions:
      - CreateNamespace=true 
      - PrunePropagationPolicy=foreground
  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: prometheus
      targetRevision: 27.28.0
      helm:
        releaseName: prometheus
        valueFiles:
        - $values/prometheus/values.yaml
        # parameters:
        #   - name: "server.service.type"
        #     value: "NodePort"
    - repoURL: https://github.com/GleidsonSCosta/kube-news.git
      targetRevision: HEAD
      ref: values
  info:
    - name: Responsável
      value: Gleidson Costa
    - name: Instalação
      value: Helm
