apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd # Mesmo namespace onde foi criado o ArgoCD.
  labels:
    curso: ArgoCD
spec:
  destination:
    namespace: argocd # Namespace onde a aplicação será publicada.
    server: https://kubernetes.default.svc
  project: default
  source:
    path: argo
    repoURL: https://github.com/GleidsonSCosta/argocd.git
    targetRevision: HEAD
    directory:
      recurse: true # Permite a recursividadade no projeto.
  syncPolicy:
    automated: # Sincronização automática
      prune: true # Permite deletar recursos que não possuem referência no manifesto
      selfHeal: true # Garante q aletrações feitas fora do GIT NÃO reflitam no ambiente
    syncOptions:
      - CreateNamespace=true #Criar namespace
      - PrunePropagationPolicy=foreground # Garante que a exclusão de recursos será feita do menor item até o maior
  info:
    - name: Responsável
      value: Gleidson Costa