apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: my-project
  namespace: argocd
spec:
  description: Projeto modelo
  sourceRepos:
    - "https://github.com/GleidsonSCosta/*"
  sourceNamespaces:
    - '*'
  destinations:
    - namespace: '!kube*'
      server: '*'
  syncWindows:
    - kind: allow
      timeZone: "America/Sao_Paulo"
      schedule: '0 17 * * *'
      duration: 2h
      applications:
      - '*'
      namespaces:
      - news